Dockerfile
FROM node:18-alpine as build

create destination directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

update and install dependency
RUN apk update && apk upgrade
RUN apk add git

copy the app, note .dockerignore
COPY . /usr/src/app/
RUN yarn install

CMD [ "yarn", "run", "dev". "--host" ]
